### ISSUE TITLE
ACE3 Configurability

### ISSUE THREAD

**Issue by jonpas** [synixebrett/HEMTT#17]
Some required configuration to satisfy CBA/ACE3/ACRE2 and other projects I want to use this project on:
- [x] Header extensions (prefix and other user-made ones) - example: `-e "version=<git-hash>"` - read from `hemtt.json` and straight passed to armake2's `cmd_build` -> #30
- [x] Signature name (`-s <signature>` in armake2) - just use instead of middle part -> #30
- [x] `@mod` folder name - template setup -> #30
- [x] Key name (bikey) - template setup -> #30
- [x] Release archive name (ACE3 does `ace3_3.1.0.zip`, CBA does `CBA_A3_v3.1.0.zip`) to zip utility - template setup -> #9 
- [x] Optionals release build path (launchable  optional mod folders) -> #132, #225 

Other:
- Disable specific warnings (`-w --warning <wname>` in armake2) - add to armake2's list of ignored warnings -> #197
- ~~Build folder (eg. armake setup with ACE3 builds into `@ace/addons` and also copies other files, that way you get a closer to release build preview, releases are probably best kept completely separate, or also not, HEMTT could resolve that easily)~~

**Comment by jonpas** [comment]
#197 was moved out of this issue.

I am considering this done, all ACE3 requirements are now satisfied.
